sudo: false

os:
  - linux

compiler:
  - gcc
  - clang

language:
  - c

services:
  - docker

before_install:
  - docker pull ebassi/grapheneci

before_script:
  - echo FROM ebassi/grapheneci > Dockerfile
  - echo ADD . /root >> Dockerfile
  - docker build -t withgit .

env:
  - BUILD_OPTS=""
  - BUILD_OPTS="-Dsse2=false"
  - BUILD_OPTS="-Dsse2=false -Dgcc_vector=false"
  - BUILD_OPTS="-Dgobject_types=false"

script:
  - docker run withgit /bin/sh -c "CC=$CC .travis/graphene-run-tests.sh $BUILD_OPTS"
