addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - libglib2.0-0
    - libglib2.0-dev
    - python3

sudo: false

language: c
compiler:
  - gcc
  - clang

script:
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
  - NOCONFIGURE=1 ./autogen.sh
  - ./configure --disable-introspection --disable-benchmarks && make && make check
  - ./configure --disable-introspection --disable-benchmarks --disable-sse2 && make && make check
  - ./configure --disable-introspection --disable-benchmarks --disable-sse2 --disable-gcc-vector && make && make check
