language: c
compiler:
  - gcc
  - clang

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-4.8 libglib2.0-0 libglib2.0-dev gtk-doc-tools

script:
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
  - NOCONFIGURE=1 ./autogen.sh
  - ./configure --disable-introspection --disable-gtk-doc --disable-benchmarks && make && make check
  - ./configure --disable-introspection --disable-gtk-doc --disable-benchmarks --disable-sse2 && make && make check
  - ./configure --disable-introspection --disable-gtk-doc --disable-benchmarks --disable-sse2 --disable-gcc-vector && make && make check
